app/general/routes.py
from flask import Blueprint

from flask import render_template, flash, redirect, url_for, request, jsonify
from werkzeug.urls import url_parse
from datetime import datetime

from app import db
from app.models import User, Projects
# import utils

import base64

general = Blueprint('general', __name__,
                   template_folder='templates')


@general.route('/', methods=['GET', 'POST'])
@general.route('/home', methods=['GET', 'POST'])
def home():
    """
    Home page 
    """
    skill_list = [0]
    projects = Projects.query.order_by(Projects.id.desc())

    for project in projects:
        item = project.skills.split(", ") 
        skill_list.insert(1, item)
        
    admin = User.query.get(1)

    return render_template('general/home.html', projects=projects, skills=skill_list,
        title='Welcome', admin=admin) 


@general.route('/project/<int:id>', methods=['GET', 'POST']) 
def project(id):
    """
    Display a specific project's information 
    
    """
    project = Projects.query.get(id)
    # imgfile = base64.b64decode(project.imgfile)
    # img_file = Projects.query.with_entities(Projects.imgfile).first()
    return render_template('general/project_info.html', project=project)

app/general/templates/general/home.html
{% extends "base.html" %}

{% block styles %}
{{ super() }}

<!-- <script type="text/javascript" src="../../../static/js/portfolio.js" defer></script> -->

{% endblock %}


{% block app_content %}

<!--- Welcome -->

<main class="site-main">
    
    <button class="scroll-to-top" id="scroll-to-top">
        <i class='bx bx-up-arrow-alt' ></i>
    </button>

    <div class="content">
        <div class="flexbox">
            <div class="span-6 about-desc">
                <div class="inner-desc">
                    <h1>Natacha Barcala </h1>
                    <h3>Software Developer, Web Developer
                    </h3>
                    <p> Computer Science graduate seeking a Software Developer role, located in Florida.
                        I primarily use Python and Flask to create web applications.
                        Come check out some of my other projects below.
                    </p>
                    <div class="">
                        <a href="{{ url_for('general.home', _anchor='portfolio') }}" class="btn border-pink">
                            Portfolio
                        </a>
                        <!-- <button href="{{ url_for('general.home', _anchor='portfolio') }}" type="button" class="btn border-pink">Portfolio</button> -->
                    </div>
                </div>
            </div>
    
            <div class="span-6 about-img">
                <img src="../../../static/img/remote-work-2.png" alt="">
            </div>
        </div>
    </div>

    <!-- About Me / Contact -->
    <section class="about-me" id='about-me'>
        <div class="container"> 
            <h5 class="small-header">About Me</h5>
            <div class="flex">
                <div class="span-6 about-me-left">
                    <h2>
                        I am looking to expand my skill set and 
                        provide value to a hard-working team.
                    </h2>
                    <p>
                        I am a motivated individual with a strong work ethic and 
                        ability to work independently. I have strong organizational and 
                        team collaboration skills with experience in improving processes.
                    </p>
    
                </div>
                <div class="span-6 about-me-right">
                    <h1 class="big-header">Contact Me</h1>
                    <p><span>Let's Talk</span></p>
                    <h2><a href="mailto:nabarcala@gmail.com" class="footer-link">nabarcala@gmail.com</a></h2>
                </div>
            </div>
        </div>
    </section>

    <!-- Services Offered -->
    <section class="services" id="services">
        <div class="container">
            <div class="text-center">
                <h5 class="small-header">Services</h5>
                <h3 class="big-header">What I Can Offer</h3>
            </div>
            <div class="services-main">
                <div class="single-service">
                    <div class="bg"></div>
                    <div class="services-inner">
                        <span class="service-python"><i class="fab fa-python"></i></span>
                        <h3>Python Developer</h3>
                        <p> I am most experienced with Python. 
                            This website was created using Python and 
                            the Flask framework! </p>
                            <a>More Coming Soon</a>
                    </div>
                </div>
                <div class="single-service active">
                    <div class="bg"></div>
                    <div class="services-inner">
                        <span class="service-web"><i class="fas fa-code"></i></span>
                        <h3>Web Designer</h3>
                        <p> Besides Python, I have used HTML, CSS, and jQuery, 
                            along with Bootstrap, the popular CSS Framework.</p>
                            <a>More Coming Soon</a>
                    </div>
                </div>
                <div class="single-service">
                    <div class="bg"></div>
                    <div class="services-inner">
                        <span class="service-hobby"><i class="fas fa-palette"></i></span>
                        <h3>Art and Etsy</h3>
                        <p> I enjoy creating artworks in my free time. 
                            This includes traditional and digital artwork. 
                            I have also created simple leather wallets! </p>
                        <!-- <p> I have created several face masks made from 100% cotton. 
                            They are available on my Etsy Store. </p> -->
                            <a href="https://www.etsy.com/shop/TachasWorkshop">More Coming Soon</a>
                    </div>
                </div>
            </div>
        </div>
    </section>

    

    <section class="portfolio" id="portfolio">
        <div class="container">
            <div class="text-center">
                <h5 class="small-header"> Portfolio </h5>
                <h3 class="big-header"> Check Out My Projects </h3>
            </div>
            <!-- https://res.cloudinary.com/nbrcl/image/upload/v1596742598/soff.png -->
            {% if projects %}
            {% for project in projects %} 
            <div class="portfolio-container">
                <img src="https://res.cloudinary.com/nbrcl/image/upload/v1596739480/{{ project.imgname + project.img_urlend }}" alt="">
                <div class="project">
                    <div class="project-i">
                        <h3>{{ project.title }}</h3>
                        <ul class="links-project">
                            {% if project.website %}
                                <a class="border-pink" href="{{ project.website }}" class="link">Live</a>
                            {% endif %}
                            {% if project.github_url %}
                                <a class="border-pink" href="{{ project.github_url }}" class="link">GitHub</a>
                            {% else %}
                            <span class="border-pink" class="link">Comming Soon</a>
                            {% endif %}
                        </ul>
                    </div>
                    <div class="project-d">
                        <p> {{ project.description }} </p> 
                        <ul class="project-tools">
                            {% for skill in skills[project.id] %}
                            <span class="grey-pill">{{ skill }}</span>
                            {% endfor %}
                            <!-- <span class="grey-pill">Tool</span>  -->
                        </ul>
                    </div>
                </div>
            </div>

            <hr>

            {% endfor %}
            {% else %}

            <div class="text-center">
                <h3 class="text-center"> Unable to get project data </h3>
            </div>

            {% endif %}

            

            </div> <!-- End of portfolio wrapper -->
        </div> 

        

    </section>

    

</main>


{% endblock %}

app/general/templates/general/project_info.html
{% extends "base.html" %}

{% block app_content %}


<div class="container-fluid project-info">

    {% if project %}

    <h1 class="text-uppercase text-center pb-5">
        {{ project.title|replace("-", " ") }}
    </h1> 

    <div class="row">
        <div class="col-lg-6 col-md-12">
            <div class="about-image pt-5">
                <img src="{{ project.imgurl }}" alt="project-img" class="img-fluid">
            </div>
        </div>
        <div class="col-lg-6 col-md-12 about-title">
            <div class="paragraph py-4 w-75">
                <p class="para">
                    {{ project.description }}
                </p>
            </div>
            <div class="row pl-3">
                <!-- <div class="col-4 pl-4">

                    {% if project.github_url %}
                    <a href="{{ project.github_url }}">
                    <button type="button" class="btn button btn-outline-primary text-uppercase">GitHub</button>
                    </a>

                    {% else %}
                    <a href="{{ project.github_url }}">
                    <button type="button" class="disabled btn button btn-outline-primary text-uppercase">GitHub</button>
                    </a>

                </div>
                {% endif %}
                <div class="col-8">

                    {% if project.website %}
                    <a href="{{ project.website }}">
                    <button type="button" class="btn button btn-outline-primary text-uppercase">Website</button>
                    </a>

                    {% else %}
                    <a href="{{ project.website }}">
                    <button type="button" class="disabled btn button btn-outline-primary text-uppercase">Website</button>
                    </a>

                    {% endif %}
                </div> -->
            </div>
        </div>
    </div>

    {% else %}

    <div class="col-lg-12 col-md-12">
        <h3 class="text-center"> Unable to get project data </h3>
    </div>

    {% endif %}

</div>

{% endblock %}

app/general/templates/general/projects.html
<div class="col-lg-4 col-md-6 col-sm-12 element-item latest">
    <div class="our-project">
        <div class="img img-thumbnail portfolio-img">
            <img src="{{ project.imgurl }}" alt="project-img" class="img-fluid">
        </div>
        <div class="title py-4">
            <h4 class="text-uppercase no-link"><a href="{{ url_for('general.project', id=project.id) }}">{{ project.title|replace("-", " ") }}</a></h4>
            <!-- <span class="text-secondary">Latest portfolio</span> -->
        </div>
    </div>
</div>