app/admin/routes.py
from flask import Blueprint
from flask import render_template, flash, redirect, url_for, request
from flask_login import current_user, login_user, logout_user, login_required
from flask_uploads import configure_uploads, IMAGES, UploadSet

from werkzeug.urls import url_parse
from datetime import datetime
import base64
import os

import cloudinary
from cloudinary.api import delete_resources_by_tag, resources_by_tag
from cloudinary.uploader import upload
from cloudinary.utils import cloudinary_url 
from cloudinary import CloudinaryImage

from app import db, uploads
from app.admin.forms import EditProjectForm, ProjectForm, EditDataForm
from app.models import User, Projects
# from app.admin.utils import check_admin

admin = Blueprint('admin', __name__,
                   template_folder='templates')

ALLOWED_EXTENSIONS = set(['png', 'jpg', 'jpeg', 'gif'])
UPLOAD_FOLDER = 'app/static/img/uploads'

def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


def check_admin():
    """
    Prevent non-admins from accessing the page
    """
    if not current_user.is_admin:
        abort(403)


@admin.route('/admin/dashboard')
@login_required
def admin_dashboard():
    """
    Show admin dashboard and prevent non-admins from accessing it.
    Admins can modify data from the dashboard
    """
    if not current_user.is_admin:
        return url_for('404.html')
    return render_template('admin/admin_dashboard.html', title='Dashboard')


@admin.route('/admin/portfolio', methods=['GET', 'POST'])
@login_required
def list_projects():
    """
    List all projects in portfolio
    """
    imgfile = []
    check_admin()
    projects = Projects.query.all()
    return render_template('admin/projects.html', projects=projects, title="Projects")


@admin.route('/admin/portfolio/add', methods=['GET', 'POST'])
@login_required
def add_project():
    """
    Create a new project to add to the portfolio.
    """
    check_admin()
    add_project = True

    form = ProjectForm()
    if form.validate_on_submit():
        # filename = uploads.save(form.imgfile.data)
        # return filename

        file = form.imgfile.data

        file_split = file.filename.rsplit('.', 1)
        filename = file_split[0]
        file_url_end = "." + file_split[1]



        flash(filename)
        # filename = file.filename
        file_upload_url = os.path.join(UPLOAD_FOLDER, filename)

        # Get image
        if filename == '':
            flash('No image selected.')
            return redirect(url_for('admin.add_project'))
        
        if file and allowed_file(file.filename): 
            file.save(file_upload_url)
            flash('Image successfully uploaded and displayed')

            response = upload ( 
                file_upload_url,
                tags="Project",
                public_id=filename,
            )
            url, options = cloudinary_url(
                response['public_id'],
                format=response['format']
            )

        # Save data to database
        projects = Projects(
            title = form.title.data,

            # imgname = file.filename, 
            # imgfile = file.read(), 
            
            # imgfile = filename,
            imgname = filename, 
            img_urlend = file_url_end,

            website = form.website.data,
            github_url = form.github_url.data,

            description = form.description.data,
            # skills = form.skills.data,
            project_type = form.project_type.data
        )
        try:
            db.session.add(projects)
            db.session.commit()
            flash('Your project post is now live!')
        except:
            flash('Error: project name already exists.')
            return redirect(url_for('admin.add_project'))

        return redirect(url_for('admin.list_projects'))

        # return imgfile.filename

    return render_template('admin/edit_form.html', form=form, title='Create a Project', action='Add', add_project=add_project)


@admin.route('/admin/portfolio/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_project(id):
    """
    Edit a project from the portfolio.
    """
    check_admin()
    add_project = False

    project = Projects.query.get_or_404(id)
    form = EditProjectForm()
    if form.validate_on_submit():
        # project.title = form.title.data
        
        if form.imgfile.data:
            file = form.imgfile.data

            file_split = file.filename.rsplit('.', 1)
            filename = file_split[0]
            file_url_end = "." + file_split[1]

            flash(filename)
            # filename = file.filename
            file_upload_url = os.path.join(UPLOAD_FOLDER, filename)

            # Get image
            
            if file and allowed_file(file.filename): 
                file.save(file_upload_url)
                flash('Image successfully uploaded and displayed')

                response = upload ( 
                    file_upload_url,
                    tags="Project",
                    public_id=filename,
                )
                url, options = cloudinary_url(
                    response['public_id'],
                    format=response['format']
                )

                project.imgname = filename
                project.img_urlend = file_url_end

        project.website = form.website.data
        project.github_url = form.github_url.data
        project.description = form.description.data
        # project.skills = form.skills.data
        project.project_type = form.project_type.data
        db.session.commit()
        flash('Project has been successfully updated.')
        return redirect(url_for('admin.list_projects'))

    form.title.data = project.title

    file = project.imgname + project.img_urlend 
    form.imgfile.data = file


    # form.imgfile.data = project.imgfile
    # form.imgurl.data = project.imgurl
    form.website.data = project.website
    form.github_url.data = project.github_url
    form.description.data = project.description
    # form.skills.data = project.skills
    form.project_type.data = project.project_type
    return render_template('admin/edit_form.html', form=form, title='Edit Project', action='Edit', add_project=add_project, project=project)


@admin.route('/admin/portfolio/delete/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_project(id):
    """
    Delete a project from the portfolio.
    """
    check_admin()

    project = Projects.query.get_or_404(id)
    db.session.delete(project)
    db.session.commit()

    flash('Project has been successfully deleted.')
    return redirect(url_for('admin.list_projects'))

    return render_template(title='Delete Project')

@admin.route('/admin/data', methods=['GET', 'POST'])
@login_required
def list_data():
    """
    List all the information for the admin to see
    """
    check_admin()
    user = User.query.filter_by(is_admin='1').first()
    return render_template('admin/information.html', admin=user, title="Admin Data")

@admin.route('/admin/data/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_data(id):
    """
    Edit personal data stored in the database
    """
    check_admin()
    edit_data = True

    user = User.query.filter_by(id='1').first()

    form = EditDataForm()
    if form.validate_on_submit():
        user.career = form.career.data
        user.headline = form.headline.data
        user.about_me = form.about_me.data

        db.session.commit()
        flash('Data has been successfully updated.')
        return redirect(url_for('admin.list_data'))

    form.career.data = user.career
    form.headline.data = user.headline
    form.about_me.data = user.about_me
    return render_template('admin/edit_form.html', form=form, title='Edit Data', action='Edit', edit_data=edit_data, admin=user)

#
# @admin.route('/admin/<username>')
# @login_required
# def user(username):
#     user = User.query.filter_by(username=username).first_or_404()
#     page = request.args.get('page', 1, type=int)
#     posts = user.posts.order_by(Post.timestamp.desc()).paginate(page, app.config['POSTS_PER_PAGE'], False)
#     next_url = url_for('admin.user', username=user.username, page=posts.next_num) \
#         if posts.has_next else None
#     prev_url = url_for('admin.user', username=user.username, page=posts.prev_num) \
#         if posts.has_prev else None
#     return render_template('admin/user.html', user=user, posts=posts.items, next_url=next_url, prev_url=prev_url)
#
# @admin.route('/admin/edit_profile', methods=['GET', 'POST'])
# @login_required
# def edit_profile():
#     form = EditProfileForm(current_user.username)
#     if form.validate_on_submit():
#         current_user.username = form.username.data
#         current_user.about_me = form.about_me.data
#         current_user.headline = form.headline.data
#         current_user.career = form.career.data
#         db.session.commit()
#         flash('Your changes have been saved.')
#         return redirect(url_for('admin.user', username=current_user.username))
#     elif request.method == 'GET':
#         form.username.data = current_user.username
#         form.about_me.data = current_user.about_me
#         form.headline.data = current_user.headline
#         form.career.data = current_user.career
#     return render_template('admin/edit_profile.html', title='Edit Profile', form=form)

app/general/routes.py
from flask import Blueprint

from flask import render_template, flash, redirect, url_for, request, jsonify
from werkzeug.urls import url_parse
from datetime import datetime

from app import db
from app.models import User, Projects
# import utils

import base64

general = Blueprint('general', __name__,
                   template_folder='templates')


@general.route('/', methods=['GET', 'POST'])
@general.route('/home', methods=['GET', 'POST'])
def home():
    """
    Home page 
    """
    skill_list = [0]
    projects = Projects.query.order_by(Projects.id.desc())

    for project in projects:
        item = project.skills.split(", ") 
        skill_list.insert(1, item)
        
    admin = User.query.get(1)

    return render_template('general/home.html', projects=projects, skills=skill_list,
        title='Welcome', admin=admin) 


@general.route('/project/<int:id>', methods=['GET', 'POST']) 
def project(id):
    """
    Display a specific project's information 
    
    """
    project = Projects.query.get(id)
    # imgfile = base64.b64decode(project.imgfile)
    # img_file = Projects.query.with_entities(Projects.imgfile).first()
    return render_template('general/project_info.html', project=project)

app/templates/base.html
{% extends 'bootstrap/base.html' %}

<!DOCTYPE html>

<html lang="en">
    <head>
        {% block metas %}
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="icon" href="data:;base64,=">
        {% endblock %}

        {% block styles %}
        <!-- Icon -->
        <link rel="shortcut icon" type="image/x-icon" href="../static/img/favicon.ico">

        <!-- BootStrap -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

        <!-- Custom CSS -->
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">

        <!-- Boxicon -->
        <link href='https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css' rel='stylesheet'>

        <!-- Add fancyBox CSS -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />

        <!-- Slick Slider CSS -->
        <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
        <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>

        {% endblock %}

        {% block title %}
            Natacha's Portfolio
        {% endblock %}
    </head>

    <body class="">
        
        {% block navbar %}   
        
        <header class="header-area">
            <nav class="navbar navbar-expand-md navbar-dark sticky-top">

                <div>
                    <a href="" class="navbar-brand border-pink">NB Portfolio</a>
                </div>

                <div class="nav-menu collapse navbar-collapse" id="nav-menu">
                    <ul class="navbar-nav ml-auto nav-list">
                        <li class="nav-item active">
                            <a class="nav-link" href="{{ url_for('general.home') }}">Home<span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('general.home', _anchor='about-me') }}">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('general.home', _anchor='services') }}">Services</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('general.home', _anchor='portfolio') }}">Portfolio</a>
                        </li>

                        {% if current_user.is_authenticated and current_user.is_admin %}

                        <li class="nav-item active">
                            <a class="nav-link" href="{{ url_for('admin.admin_dashboard') }}">Dashboard<span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                        </li>

                        {% elif current_user.is_authenticated and current_user.is_admin == 0 %}

                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                        </li>

                        {% endif %}

                    </ul>
                </div>

                <div class="nav-toggle" id="nav-toggle">
                    <i class='bx bx-menu menu'></i> 
                </div>
            </nav>
        </header>

        {% endblock %}

        {% block content %}  
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-info" role="alert">{{ message }}</div>
                    {% endfor %}
                {% endif %}
            {% endwith %}

            {# application content needs to be provided in the app_content block #}
            {% block app_content %}{% endblock %}

        <footer class="footer">
            <div class="container">
                <div class="social-icons text-center">
                    <a href="https://linkedin.com/in/natacha-barcala"><i class="fab fa-linkedin"></i></a>
                    <a href="https://github.com/nabarcala"><i class="fab fa-github"></i></a>
                    <a href="#"><i class="fab fa-instagram"></i></a>
                    <a href="https://www.etsy.com/shop/TachasWorkshop"><i class="fab fa-etsy"></i></a>
                </div>
                <div class="copyrights text-center">
                    Copyright &copy; 2020 All rights reserved
                </div>
            </div>
        </footer>

        {% endblock %}
        
    </body>

    

</html>



{% block scripts %}
{{ super() }}

<!-- AJAX and BootStrap -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

<!-- Font Awesome -->
<script src="https://kit.fontawesome.com/d0e300c793.js" crossorigin="anonymous"></script>

<!-- fancyBox -->
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>

<!-- Slick Slider -->
<script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>

<script type="text/javascript" src="../../../static/js/portfolio.js" defer></script>
<script type="text/javascript" src="../../../static/js/main.js" defer></script>



{{ moment.include_moment() }}
{% endblock %}

app/templates/projects.html
{% extends 'bootstrap/base.html' %}

{% block app_content %}
    <div class="card d-flex align-items-center">
        <img
             class="card-img-top"
             src="{{ url_for('images', filename=project.imgfile, width=300) }}"
             alt="card image cap">
        <div class="card-body">
        <h5 class="card-title">{{ project.title|replace("-", " ") }}</h5>
        <p class="card-text">{{ project.long_desc }}</p>

        {% if project.abandoned %}
            <p class="abandoned">** Abandoned</p>
        {% endif %}

        <div class="d-flex flex-wrap">
            {% if project.website %}
                <a
                    href="{{ project.website }}"
                    target="_blank"
                    class="card-link"
                ><i class="fas fa-globe"></i> Website</a>
            {% endif %}
            <a
                href="{{ project.github_url }}"
                target="_blank"
                class="card-link"
            ><i class="fab fa-github"></i> GitHub Repo</a>
            <a
                href="#"
                class="card-link"
                id="backlink"
            ><i class="fas fa-arrow-left"></i> Go Back</a>
        </div>
    </div>
    </div>
{% endblock %}